config/routes.rb
Rails.application.routes.draw do
  get 'qr_codes/new'
  get 'qr_codes/create'
  # devise_for :users
  # devise_for :users, controllers: {
  #   sessions: 'users/sessions'
  # }
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'basic-qr-code-reader', to: 'basic_qr_codes#index'
  root to: 'pages#home' do
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :restaurants do
    resources :orders
    resources :tables do
      resources :orders do
        resources :dishes
        resources :people
      end
    end
    resources :menus do
      resources :categories do
        resources :dishes
      end
      resources :dishes
    end
    resources :dishes
  end

  # resources :tables do
  #   resources :orders, only: [:index, :new, :create, :show, :edit, :update] do
  #     member do
  #       get :confirmation
  #     end
  #   end
  # end

  resources :restaurants do
    resources :tables do
      resources :orders do
        member do
          get :confirmation
        end
      end
    end
  end

  resources :order_dishes, only: [:edit]

  get :ready_order_dish, to: 'order_dishes#ready'

  get :pay_order_dish, to: 'order_dishes#pay'

  get :paid_order_dish, to: 'order_dishes#paid'

  get :command_order_dish, to: 'order_dishes#command'

  get :cook_order_dish, to: 'order_dishes#cook'

  # get :add_order_dish, to: 'orders#addone', as: 'command'
  # get 'orders/:order_id/dishes/:id/order_dishes/new', to: 'orders#addone', as: 'command'
  get 'restaurants/:restaurant_id/tables/:table_id/orders/:order_id/order_dishes/new', to: 'orders#addone', as: 'command'
  get 'restaurants/:restaurant_id/tables/:table_id/orders/:order_id/confirm', to: 'orders#confirm', as: 'confirm'
  get 'restaurants/:restaurant_id/tables/:table_id/orders/:order_id/dishes/:id/order_dishes/new', to: 'dishes#seeone', as: 'see'
  #deete people
  get 'restaurants/:restaurant_id/tables/:table_id/orders/:order_id/people/:id/destroy', to: 'people#destroy', as: 'destroyperson', data: { confirm: "Are you sure?" }
  #delete table
  get 'restaurants/:restaurant_id/tables/:id/destroy', to: 'tables#destroy', as: 'destroytable', data: { confirm: "Are you sure?" }
  #delete catagory
  get 'restaurants/:restaurant_id/menus/:menu_id/categories/:id/destroy', to: 'categories#destroy', as: 'destroycategory', :data => { :confirm => "Are you sure?" }
  # delete dish
  get 'restaurants/:restaurant_id/dishes/:id/destroy', to: 'dishes#destroy', as: 'destroydish', :data => { :confirm => "Are you sure?" }
  #route for pdf
  get 'restaurants/:restaurant_id/tables/:table_id/qr.pdf', to: 'tables#qr', as: 'qr'
  #activate menu
  get 'restaurants/:restaurant_id/menus/:menu_id/activate', to: 'menus#activate', as: 'activemenu', :data => { :confirm => "Are you sure?" }

  resources :orders do
    resources :dishes, only: :show
  end

  resources :qr_codes, only: [:new, :create]

  get 'qr_codes', to: "qr_codes#new"

  resources :tables

  get '/design', to: 'pages#design'



end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :order, optional: true
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create, :show, :confirmation, :edit, :update ]
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = policy_scope(Person)
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])
    authorize @person
  end

  # GET /people/new
  def new
    @person = Person.new
    @person.order = Order.find(params[:order_id])
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)
    @person.order = Order.find(params[:order_id])
    authorize @person
    @person.save
    # respond_to do |format|
    #   if @person.save
    #     format.html { redirect_to @person, notice: 'Person was successfully created.' }
    #     format.json { render :show, status: :created, location: @person }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @person.errors, status: :unprocessable_entity }
    #   end
    # end
    redirect_to restaurant_table_order_path(@person.order.table.restaurant, @person.order.table, @person.order)
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    # respond_to do |format|
    #   if @person.update(person_params)
    #     format.html { redirect_to @person, notice: 'Person was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @person }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @person.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    # respond_to do |format|
    #   format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
    @person = Person.find(params[:id])
    authorize @person
    @person.destroy
    redirect_to restaurant_table_order_people_path(@person.order.table.restaurant, @person.order.table, @person.order)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      # params.fetch(:person, {})
      params.require(:person).permit(:firstname, :lastname, :phone)
    end
end

app/views/people/_form.html.erb
<%= simple_form_for [restaurant, table, order, person ] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <!-- <div class="form-inputs">
    <%#= f.label :firstname %>
    <%#= f.text_field :firstname %>
    <%#= f.label :lastname %>
    <%#= f.text_field :lastname %>
    <%#= f.label :phone %>
    <%#= f.text_field :phone %>
  </div> -->

  <!-- <div class="form-actions">
    <%#= f.button :submit, placeholder: "add" %>
  </div> -->
<% end %>

<div class="d-flex justify-content-around" style="width: 100%; ">
  <%= simple_form_for [restaurant, table, order, person ] do |f| %>
  <div>
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <%= person.firstname %>
        <td><%= link_to 'Show', restaurant_table_order_person_path(person.order.table.restaurant, person.order.table, person.order, person) %></td>
        <td><%= link_to 'Edit', edit_restaurant_table_order_person_path(person.order.table.restaurant, person.order.table, person.order, person) %></td>
        <td><%= link_to 'Destroy', destroyperson_path(person.order.table.restaurant, person.order.table, person.order, person), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Person', new_restaurant_table_order_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_restaurant_table_order_person_path(@person.order.table.restaurant, @person.order.table, @person.order, @person) %> |
<%= link_to 'Back', restaurant_table_order_people_path %>