config/routes.rb
Rails.application.routes.draw do
  get 'qr_codes/new'
  get 'qr_codes/create'
  # devise_for :users
  # devise_for :users, controllers: {
  #   sessions: 'users/sessions'
  # }
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'basic-qr-code-reader', to: 'basic_qr_codes#index'
  root to: 'pages#home' do
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :restaurants do
    resources :orders
    resources :tables do
      resources :orders do
        resources :dishes
        resources :people
      end
    end
    resources :menus do
      resources :categories do
        resources :dishes
      end
      resources :dishes
    end
    resources :dishes
  end

  # resources :tables do
  #   resources :orders, only: [:index, :new, :create, :show, :edit, :update] do
  #     member do
  #       get :confirmation
  #     end
  #   end
  # end

  resources :restaurants do
    resources :tables do
      resources :orders do
        member do
          get :confirmation
        end
      end
    end
  end

  resources :order_dishes, only: [:edit]

  get :ready_order_dish, to: 'order_dishes#ready'

  get :pay_order_dish, to: 'order_dishes#pay'

  get :paid_order_dish, to: 'order_dishes#paid'

  get :command_order_dish, to: 'order_dishes#command'

  get :cook_order_dish, to: 'order_dishes#cook'

  # get :add_order_dish, to: 'orders#addone', as: 'command'
  # get 'orders/:order_id/dishes/:id/order_dishes/new', to: 'orders#addone', as: 'command'
  get 'restaurants/:restaurant_id/tables/:table_id/orders/:order_id/order_dishes/new', to: 'orders#addone', as: 'command'
  get 'restaurants/:restaurant_id/tables/:table_id/orders/:order_id/confirm', to: 'orders#confirm', as: 'confirm'
  get 'restaurants/:restaurant_id/tables/:table_id/orders/:order_id/dishes/:id/order_dishes/new', to: 'dishes#seeone', as: 'see'
  #deete people
  get 'restaurants/:restaurant_id/tables/:table_id/orders/:order_id/people/:id/destroy', to: 'people#destroy', as: 'destroyperson', data: { confirm: "Are you sure?" }
  #delete table
  get 'restaurants/:restaurant_id/tables/:id/destroy', to: 'tables#destroy', as: 'destroytable', data: { confirm: "Are you sure?" }
  #delete catagory
  get 'restaurants/:restaurant_id/menus/:menu_id/categories/:id/destroy', to: 'categories#destroy', as: 'destroycategory', :data => { :confirm => "Are you sure?" }
  # delete dish
  get 'restaurants/:restaurant_id/dishes/:id/destroy', to: 'dishes#destroy', as: 'destroydish', :data => { :confirm => "Are you sure?" }
  #route for pdf
  get 'restaurants/:restaurant_id/tables/:table_id/qr.pdf', to: 'tables#qr', as: 'qr'
  #activate menu
  get 'restaurants/:restaurant_id/menus/:menu_id/activate', to: 'menus#activate', as: 'activemenu', :data => { :confirm => "Are you sure?" }

  resources :orders do
    resources :dishes, only: :show
  end

  resources :qr_codes, only: [:new, :create]

  get 'qr_codes', to: "qr_codes#new"

  resources :tables

  get '/design', to: 'pages#design'



end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  def index
    @tables = policy_scope(Table)
    @table = Table.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def show
    if params[:id] == "qr"
      @restaurant =Restaurant.find(params[:restaurant_id])
      @tables = Table.all
      authorize @tables
    else
      @restaurant =Restaurant.find(params[:restaurant_id])
      @table = Table.find(params[:id])
      @orders = @table.orders
      authorize @table
    end
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @table = Table.new
    authorize @table
  end

  def qr
    # require "prawn"
    @tables = Table.all
    @table = Table.find(params[:table_id])
    @restaurant = @table.restaurant
    authorize @table
  end

  def destroy
    @table = Table.find(params[:id])
    @restaurant = @table.restaurant
    @table.destroy
    authorize @table
    redirect_to restaurant_tables_path(@restaurant)
  end

  def create
    @url = request.original_url
    @restaurant = Restaurant.find(params[:restaurant_id])
    x = 1
    while @restaurant.tables.find_by(number: x) != nil do
        x += 1
        end
      @table = Table.new(number: x)
      # @table = Table.new(table_params)
      @table.restaurant = Restaurant.find(params[:restaurant_id])
      authorize @table

      qrcode = RQRCode::QRCode.new("http://pladujoor.xyz/tables/table_#{@table.id}/orders/new")

      # NOTE: showing with default options specified explicitly
      png = qrcode.as_png(
        bit_depth: 1,
        border_modules: 4,
        color_mode: ChunkyPNG::COLOR_GRAYSCALE,
        color: 'black',
        file: nil,
        fill: 'white',
        module_px_size: 6,
        resize_exactly_to: false,
        resize_gte_to: false,
        size: 120
      )

      IO.binwrite("app/assets/images/table_#{@table.number}.png", png.to_s)
      # @qrcode = "tables/table_#{@table.number}.png"

      if @table.save!
        redirect_to restaurant_tables_path(@restaurant)
      else
        render 'new'
      end
    end


  end

  def edit
    @table = Table.find(params[:id])
    authorize @table
  end

  def update
      @table = Table.find(params[:id])
    @table.save
    redirect_to table_path(@table)
  end

  private

  def table_params
    params.require(:table).permit(:number, :qrcode)
  end

app/views/tables/index.html.erb
<div class="tablesh2">
  <h2>Your tables</h2>
  <%= render "shared/table_form", restaurant: @restaurant, table: @table %>
</div>
<div class="card-index" >
  <div class="column" >
    <% @restaurant.tables.each do |table| %>
      <div class="card-full" >
        <% if policy(table).show? %>
          <%= link_to restaurant_table_path(restaurant_id: @restaurant.id, id: table.id), class: "d-flex" do  %>
            <div class="card-table-index">
              <h1><%= table.number %> - <%= table.orders.count %> order(s) - <%= table.order_dishes.count %> dishes</h1>
              <!-- <p><%#= table.description %></p> -->
              <%= image_tag "table_#{table.number}.png", alt: "", :style=> "height: 200px" %>
            </div>
          <% end %>
        <% end %>
      </div>
      <%= link_to "delete table", destroytable_path(@restaurant, table), method: :delete %>
      <%= link_to "create order", new_restaurant_table_order_path(@restaurant, table)  %>
    <% end %>
  </div>
</div>

app/views/tables/new.html.erb
<h1>Restaurant</h1>
<%= simple_form_for ([ @restaurant ]) do |f| %>
  <%= f.input :name %>
  <%#= f.input :description %>
  <%= f.submit %>
<% end %>

app/views/tables/show.html.erb
<h1>Table <%= @table.number %></h1>
<%= image_tag "table_#{@table.number}.png", alt: "", :style=> "height: 200px" %>
<p>Find me in app/views/tables/show.html.erb</p>
<%= link_to "create order", new_restaurant_table_order_path(@restaurant, @table)  %>
<div style="display: flex">
  <div>
    <h4>Commands</h4>
    <%  @orders.each do | order | %>
        <%= link_to edit_restaurant_table_order_path(@restaurant, @table, order) do  %>
    <div style="border: solid; border-color: black">
      <p><%= order.id %> status:<%= order.status %> <%= distance_of_time_in_words(Time.now, order.created_at) %></p>
      <% order.order_dishes.each do |od| %>
          <div><%= od.dish.name %></div>
        <% end %>
    </div>
      <% end %>
    <% end %>
  </div>
</div>
<%= link_to "Delete table", destroytable_path(@table.restaurant, @table) %>