config/routes.rb
Rails.application.routes.draw do
  get 'qr_codes/new'
  get 'qr_codes/create'
  # devise_for :users
  # devise_for :users, controllers: {
  #   sessions: 'users/sessions'
  # }
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'basic-qr-code-reader', to: 'basic_qr_codes#index'
  root to: 'pages#home' do
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :restaurants do
    resources :orders
    resources :tables do
      resources :orders do
        resources :dishes
        resources :people
      end
    end
    resources :menus do
      resources :categories do
        resources :dishes
      end
      resources :dishes
    end
    resources :dishes
  end

  # resources :tables do
  #   resources :orders, only: [:index, :new, :create, :show, :edit, :update] do
  #     member do
  #       get :confirmation
  #     end
  #   end
  # end

  resources :restaurants do
    resources :tables do
      resources :orders do
        member do
          get :confirmation
        end
      end
    end
  end

  resources :order_dishes, only: [:edit]

  get :ready_order_dish, to: 'order_dishes#ready'

  get :pay_order_dish, to: 'order_dishes#pay'

  get :paid_order_dish, to: 'order_dishes#paid'

  get :command_order_dish, to: 'order_dishes#command'

  get :cook_order_dish, to: 'order_dishes#cook'

  # get :add_order_dish, to: 'orders#addone', as: 'command'
  # get 'orders/:order_id/dishes/:id/order_dishes/new', to: 'orders#addone', as: 'command'
  get 'restaurants/:restaurant_id/tables/:table_id/orders/:order_id/order_dishes/new', to: 'orders#addone', as: 'command'
  get 'restaurants/:restaurant_id/tables/:table_id/orders/:order_id/confirm', to: 'orders#confirm', as: 'confirm'
  get 'restaurants/:restaurant_id/tables/:table_id/orders/:order_id/dishes/:id/order_dishes/new', to: 'dishes#seeone', as: 'see'
  #deete people
  get 'restaurants/:restaurant_id/tables/:table_id/orders/:order_id/people/:id/destroy', to: 'people#destroy', as: 'destroyperson', data: { confirm: "Are you sure?" }
  #delete table
  get 'restaurants/:restaurant_id/tables/:id/destroy', to: 'tables#destroy', as: 'destroytable', data: { confirm: "Are you sure?" }
  #delete catagory
  get 'restaurants/:restaurant_id/menus/:menu_id/categories/:id/destroy', to: 'categories#destroy', as: 'destroycategory', :data => { :confirm => "Are you sure?" }
  # delete dish
  get 'restaurants/:restaurant_id/dishes/:id/destroy', to: 'dishes#destroy', as: 'destroydish', :data => { :confirm => "Are you sure?" }
  #route for pdf
  get 'restaurants/:restaurant_id/tables/:table_id/qr.pdf', to: 'tables#qr', as: 'qr'
  #activate menu
  get 'restaurants/:restaurant_id/menus/:menu_id/activate', to: 'menus#activate', as: 'activemenu', :data => { :confirm => "Are you sure?" }

  resources :orders do
    resources :dishes, only: :show
  end

  resources :qr_codes, only: [:new, :create]

  get 'qr_codes', to: "qr_codes#new"

  resources :tables

  get '/design', to: 'pages#design'



end

app/models/dish.rb
class Dish < ApplicationRecord
  include PgSearch::Model

  has_many :order_dishes
  has_many :orders, through: :order_dishes
  belongs_to :category, optional: true
  belongs_to :restaurant, optional: true
  has_many :category_dishes
  has_one_attached :photo
  monetize :price_cents


end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :categories
  belongs_to :restaurant
  has_many :dishes, through: :categories
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :seeone]
  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @dishes = policy_scope(Dish)
  end

  def show
    if params[:order_id] == nil
        @dish = Dish.find(params[:id])
        authorize @dish
      else
        @order = Order.find(params[:order_id])
        @table = @order.table
        @dish = Dish.find(params[:id])
        @restaurant = Restaurant.find(params[:restaurant_id])
        @dishe_ids_with_quantity = @order.order_dishes.group(:dish_id).count
    # @order_dish = OrderDish.create(dish_id: params[:id], order: Order.find(params[:order_id]), status: "Commandé")
        authorize @dish
    end
  end

  def seeone
    @restaurant = Restaurant.find(params[:restaurant_id])
    @table = Table.find(params[:table_id])
    @order = Order.find(params[:order_id])
    @dish = Dish.find(params[:id])
    OrderDish.create(dish_id: @dish.id, order: @order, status: "Commandé")
    authorize @dish
    redirect_to edit_restaurant_table_order_path(@order.table.restaurant, @order.table, @order, anchor: "dish-#{@dish.id}")
  end

  def new
    @dish = Dish.new
    @restaurant = Restaurant.find(params[:restaurant_id])
    if Menu.find(params[:menu_id]) != nil
      @menu = Menu.find(params[:menu_id])
    end
    if Category.find(params[:category_id])!= nil
      @category = Category.find(params[:category_id])
      @dish.category = @category
    end
    authorize @dish
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    if @menu != nil
      @menu = Menu.find(params[:menu_id])
    end
    @dish = Dish.new(dish_params)
    @category = Category.find(params[:dish][:category_id])
    @dish.category_id = @category.id
    @dish.restaurant = @restaurant
    authorize @dish
    if @dish.save!
      redirect_to restaurant_menu_path(@restaurant, @menu)
    else
      render "new"
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:restaurant_id])
    @dish = Dish.find(params[:id])
    authorize @dish
  end

  def update
    @dish = Dish.find(params[:id])
    authorize @dish
    @dish.update(dish_params)
    redirect_to restaurant_dish_path(@dish.restaurant, @dish)
  end

  def destroy
    @dish = Dish.find(params[:id])
    @restaurant = Restaurant.find(params[:restaurant_id])
    authorize @dish
    @dish.destroy
    redirect_to restaurant_dishes_path(@restaurant)
  end

  private

  def dish_params
    params.require(:dish).permit(:name, :ingredient, :quantity, :duration, :price, :photo, :category, :deactivated)
  end
end

app/views/dishes/_editorder.html.erb
<%= simple_form_for [@restaurant, table, currentorder] do |f| %>
<div class='lastcontainer'>
  <div class='btnbottom' data-controller="change-qty">
    <%= simple_fields_for :order_dishes do |od| %>
      <% @dishe_ids_with_quantity.each do |dish_id, dish_quantity| %>
        <% if dish_id != dish.id %>
          <%# re-add the other dishes as hidden inputs %>
          <%= od.input dish_id, as: :hidden, input_html: { value: dish_quantity } %>
        <% else %>
          <%# dish already added, add - / + buttons %>
          <div class='btnqty2'>
            <div class="btn-lessmax" data-action="click->change-qty#minus" style= "cursor: pointer;">-</div>
            <%= od.input(
                  dish.id,
                  readonly: true,
                  label: false,
                  wrapper_html: {style: "margin: 0;"},
                  input_html: {
                    value: currentorder.dishes.count { |e| e == dish },
                    style: "background-color: white; border-color: white ; color: black; width: 50px; text-align: center; font-size: 32px;%",
                    data: {target: "change-qty.input"}
                  }
                ) %>
            <div class="btn-plusmax" data-action="click->change-qty#plus" style= "cursor: pointer;">+</div>
          </div>
        <% end %>
      <% end %>

      <%# dish not already added, add - / + buttons %>
      <% unless currentorder.dish_ids.include?(dish.id) %>
        <div class='btnqty2'>
            <div class="btn-plus2" data-action="click->change-qty#minus" style= "cursor: pointer;">-</div>
            <%= od.input(
                  dish.id,
                  readonly: true,
                  label: false,
                  wrapper_html: {style: "margin: 0;"},
                  input_html: {
                    value: 0,
                    style: "background-color: white; border-color: white ; color: black; width: 70px; text-align: center; font-size: 32px;",
                    data: {target: "change-qty.input"}
                  }
                ) %>
            <div class="btn-plus2" data-action="click->change-qty#plus" style= "cursor: pointer;">+</div>
          </div>
      <% end %>
    <% end %>

    <%= f.submit "UPDATE", class: "btnaddmodal" %>
  </div>
</div>
<% end %>

app/views/dishes/destroy.html.erb
<h1>Dishes#destroy</h1>
<p>Find me in app/views/dishes/destroy.html.erb</p>

app/views/dishes/edit.html.erb
<h1>Dishes#new</h1>
<p>Find me in app/views/dishes/new.html.erb</p>
<%#= render "shared/dishe_form", dishe: @dishe%>
<%= simple_form_for ([ @restaurant, @dish ]) do |f| %>

  <%= f.input :name %>
  <%= f.input :ingredient %>
  <%= f.input :quantity %>
  <%= f.input :duration %>
  <%= f.input :price %>
  <%= f.association :category%>
  <%= f.input :deactivated %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/dishes/index.html.erb
<h1>Dishes#index</h1>
<p>Find me in app/views/dishes/index.html.erb</p>
<h2><%= @restaurant.dishes.count %> dishes</h2>

<%= link_to "Add a dish", new_restaurant_dish_path(@restaurant)  %>
<%  @restaurant.dishes.each do | dish | %>
<p><%= link_to dish.id,  restaurant_dish_path(dish.restaurant, dish) %><%= dish.name %> <%= dish.deactivated ? "deactivated" : "activated" %></p>
<% end %>

app/views/dishes/new.html.erb
<h1>Dishes#new</h1>
<p>Find me in app/views/dishes/new.html.erb</p>
<%#= render "shared/dishe_form", dishe: @dishe%>
<%= simple_form_for ([ @restaurant, @dish ]) do |f| %>

  <%= f.input :name %>
  <%= f.input :ingredient %>
  <%= f.input :quantity %>
  <%= f.input :duration %>
  <%= f.input :price %>
  <%= f.input :deactivated %>
  <%= f.association :category, collection: Category.where(restaurant_id: @restaurant.id) %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/dishes/show.html.erb
<% if @order == nil %>
    <div class='showtextcontainer'>
      <div class='showtitleprice'>
        <h2><%= @dish.name %></h2>
        <h2><%= @dish.quantity %></h2>
        <h2><%= @dish.price %>€</h2>
      </div>
      <p><%= @dish.ingredient %></p>
      <%= @dish.deactivated ? "deactivated" : "activated" %>
    </div >
    <% if current_user != nil && @dish.restaurant.user_id == current_user.id %>
      <%= link_to "edit", edit_restaurant_dish_path(@dish.restaurant, @dish)%>
      <%= link_to "restaurant" , restaurant_path(@dish.restaurant) %>
      <%= link_to "delete", destroydish_path(@dish.restaurant) %>
    <% end %>
    <%#= link_to add_order_dish_path(@order_dish) do %>
      <!-- <div>yo2</div> -->
    <%# end %>

  <% else %>
    <div class='top-page'>
    <div class='top-left'>
      <%= link_to edit_restaurant_table_order_path(@order.table.restaurant, @order.table, @order), data: { turbolinks: 'false' } do %>
        <i class="fas fa-angle-left btn-back"></i>
      <% end %>
    </div>
      <div class='top-right'>
        <h1>@restaurant.name</h1>
      </div>
    </div>

    <div class='showcontainer'>
    <% if @dish.photo.attached? %>
          <%= cl_image_tag @dish.photo.key , :class => "showimg" %>
          <% end %>
    </div>

    <div class='showtextcontainer'>
      <div class='showtitleprice'>
        <h2><%= @dish.name %></h2>
        <h2><%= @dish.quantity %></h2>
        <h2><%= @dish.price %>€</h2>
      </div>
      <p><%= @dish.ingredient %></p>
    </div >

    <%= simple_form_for [@restaurant, @table, @order] do |f| %>
      <% if @dish.quantity > 0 %>
        <div class='btnbottom' data-controller="change-qty">
          <%= simple_fields_for :order_dishes do |od| %>
            <% @dishe_ids_with_quantity.each do |dish_id, dish_quantity| %>
              <% if dish_id != @dish.id %>
                <%# re-add the other dishes as hidden inputs %>
                <%= od.input dish_id, as: :hidden, input_html: { value: dish_quantity } %>
              <% else %>
                <%# dish already added, add - / + buttons %>
                <div class='btnqty'>
                  <div class="btn-lessmax" data-action="click->change-qty#minus" style= "cursor: pointer;">-</div>
                  <%= od.input(
                        @dish.id,
                        readonly: true,
                        label: false,
                        wrapper_html: {style: "margin: 0;"},
                        input_html: {
                          value: @order.dishes.count { |e| e == @dish },
                          style: "background-color: white; border-color: white ; color: black; width: 50px; text-align: center; font-size: 32px;%",
                          data: {target: "change-qty.input"}
                        }
                      ) %>
                  <div class="btn-plusmax" data-action="click->change-qty#plus" style= "cursor: pointer;">+</div>
                </div>
              <% end %>
            <% end %>

            <%# dish not already added, add - / + buttons %>
            <% unless @order.dish_ids.include?(@dish.id) %>
              <div class='btnqty'>
                  <div class="btn-plus2" data-action="click->change-qty#minus" style= "cursor: pointer;">-</div>
                  <%= od.input(
                        @dish.id,
                        readonly: true,
                        label: false,
                        wrapper_html: {style: "margin: 0;"},
                        input_html: {
                          value: 0,
                          style: "background-color: white; border-color: white ; color: black; width: 50px; text-align: center; font-size: 32px;",
                          data: {target: "change-qty.input"}
                        }
                      ) %>
                  <div class="btn-plus2" data-action="click->change-qty#plus" style= "cursor: pointer;">+</div>
                </div>
            <% end %>
          <% end %>

          <%= f.submit "UPDATE", class: "btnadd" %>
        </div>
      <% end %>
    <% end %>
<% end %>
<div data-controller="counter">
      <%#= link_to see_path(@restaurant, @table, @order, @dish) do %>

        <!-- <div data-action="click->counter#refresh">yo23</div> -->
      <%# end %>
    </div>