config/routes.rb
Rails.application.routes.draw do
  get 'qr_codes/new'
  get 'qr_codes/create'
  # devise_for :users
  # devise_for :users, controllers: {
  #   sessions: 'users/sessions'
  # }
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'basic-qr-code-reader', to: 'basic_qr_codes#index'
  root to: 'pages#home' do
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :restaurants do
    resources :orders
    resources :tables do
      resources :orders do
        resources :dishes
        resources :people
      end
    end
    resources :menus do
      resources :categories do
        resources :dishes
      end
      resources :dishes
    end
    resources :dishes
  end

  # resources :tables do
  #   resources :orders, only: [:index, :new, :create, :show, :edit, :update] do
  #     member do
  #       get :confirmation
  #     end
  #   end
  # end

  resources :restaurants do
    resources :tables do
      resources :orders do
        member do
          get :confirmation
        end
      end
    end
  end

  resources :order_dishes, only: [:edit]

  get :ready_order_dish, to: 'order_dishes#ready'

  get :pay_order_dish, to: 'order_dishes#pay'

  get :paid_order_dish, to: 'order_dishes#paid'

  get :command_order_dish, to: 'order_dishes#command'

  get :cook_order_dish, to: 'order_dishes#cook'

  # get :add_order_dish, to: 'orders#addone', as: 'command'
  # get 'orders/:order_id/dishes/:id/order_dishes/new', to: 'orders#addone', as: 'command'
  get 'restaurants/:restaurant_id/tables/:table_id/orders/:order_id/order_dishes/new', to: 'orders#addone', as: 'command'
  get 'restaurants/:restaurant_id/tables/:table_id/orders/:order_id/confirm', to: 'orders#confirm', as: 'confirm'
  get 'restaurants/:restaurant_id/tables/:table_id/orders/:order_id/dishes/:id/order_dishes/new', to: 'dishes#seeone', as: 'see'
  #deete people
  get 'restaurants/:restaurant_id/tables/:table_id/orders/:order_id/people/:id/destroy', to: 'people#destroy', as: 'destroyperson', data: { confirm: "Are you sure?" }
  #delete table
  get 'restaurants/:restaurant_id/tables/:id/destroy', to: 'tables#destroy', as: 'destroytable', data: { confirm: "Are you sure?" }
  #delete catagory
  get 'restaurants/:restaurant_id/menus/:menu_id/categories/:id/destroy', to: 'categories#destroy', as: 'destroycategory', :data => { :confirm => "Are you sure?" }
  # delete dish
  get 'restaurants/:restaurant_id/dishes/:id/destroy', to: 'dishes#destroy', as: 'destroydish', :data => { :confirm => "Are you sure?" }
  #route for pdf
  get 'restaurants/:restaurant_id/tables/:table_id/qr.pdf', to: 'tables#qr', as: 'qr'
  #activate menu
  get 'restaurants/:restaurant_id/menus/:menu_id/activate', to: 'menus#activate', as: 'activemenu', :data => { :confirm => "Are you sure?" }

  resources :orders do
    resources :dishes, only: :show
  end

  resources :qr_codes, only: [:new, :create]

  get 'qr_codes', to: "qr_codes#new"

  resources :tables

  get '/design', to: 'pages#design'



end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_one_attached :photo
  has_many :tables
  has_many :orders, through: :tables
  has_many :order_dishes, through: :orders
  has_many :menus
  has_many :dishes
  belongs_to :user
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = policy_scope(Restaurant)
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @tables = @restaurant.orders
    authorize @restaurant
  end

  def new
    @restaurant = Restaurant.new
    authorize @restaurant
  end

  def create
    @user = current_user
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user_id = @user.id
    authorize @restaurant
    if @restaurant.save!
      redirect_to restaurant_path(@restaurant)
    else
      render "new"
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
    @restaurant.destroy
    redirect_to restaurants_path
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :email, :address, :color1, :color2, :color3, :photo, :ownerfirstname, :ownerlastname)
  end
end

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/edit.html.erb
<%#= render "shared/restaurant_form", restaurant: @restaurant %>
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :telephone %>
  <%= f.input :address %>
  <%= f.input :ownerfirstname %>
  <%= f.input :ownerlastname %>
  <%= f.input :color1 %>
  <%= f.input :color2 %>
  <%= f.input :color3 %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurants#index</h1>
<p>Find me in app/views/restaurants/index.html.erb</p>
<%= link_to "Add a restaurant", new_restaurant_path %>
<% @restaurants.each do |restaurant| %>
  <%= link_to restaurant_path(restaurant) do %>
    <h1><%= restaurant.name %></h1>
  <% end %>
<% end %>

app/views/restaurants/new.html.erb
<h1>Restaurants#new</h1>
<p>Find me in app/views/restaurants/new.html.erb</p>
<%#= render "shared/restaurant_form", restaurant: @restaurant %>
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :telephone %>
  <%= f.input :address %>
  <%= f.input :ownerfirstname %>
  <%= f.input :ownerlastname %>
  <%= f.input :color1 %>
  <%= f.input :color2 %>
  <%= f.input :color3 %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<div class="header-restaurants" style="background-color: <%= @restaurant.color1 %>; ">
  <div class="header-restaurants-title" >
    <% if @restaurant.photo.attached? %>
      <%= cl_image_tag @restaurant.photo.key, :transformation=>[
      {:width=>300, :height=>400, :crop=>"fill"},
      ] %>
    <% else %>
      <img src="logo.jpd" alt="">
    <% end %>

  </div>
</div>
<div  style="display: flex; background-color: <%= @restaurant.color1 %>; color: white; justify-content: center; padding-bottom: 100px">
  <!-- <h1><%#= @restaurant.name %></h1> -->

  <!-- <h1>Restaurants#show</h1> -->
  <!-- <p>Find me in app/views/restaurants/show.html.erb</p> -->
  <div style="text-align: center">
    <h2><%= @restaurant.orders.count %> order(s)</h2>
    <h5><%= @restaurant.order_dishes.count %> dish(es)</h5>
    <div>
      <%= link_to "See all orders", restaurant_orders_path(@restaurant) %>
    </div>
    <h2><%= @restaurant.tables.count %> table(s)</h2>
    <div>
      <%= link_to "See all tables", restaurant_tables_path(@restaurant) %>
    </div>
    <h2><%= @restaurant.menus.count %> menus</h2>
    <div>
      <%= link_to  "See all menus", restaurant_menus_path(@restaurant)  %>
    </div>
    <h2><%= @restaurant.dishes.count %> dishes</h2>
    <div>
      <%= link_to  "See all dishes", restaurant_dishes_path(@restaurant)  %>
    </div>
  </div>
</div>